spring:
  application:
    name: ms-library-operator
  datasource:
    url: jdbc:postgresql://localhost:5432/OperatorDB
    username: postgres
    password: Root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
## Configuración de instancia
server:
  port: 8090


## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-library-operator

## Configuracion secundaria (custom)
getBook:
  url: http://ms-library-online/books/%s